export const DIRECTIONS_INTERN = [
    {text: 'HR', id: 'direction_intern_0'},
    {text: 'Административный персонал', id: 'direction_intern_1'},
    {text: 'Аналитика', id: 'direction_intern_2'},
    {text: 'Дизайн', id: 'direction_intern_3'},
    {text: 'Маркетинг и PR', id: 'direction_intern_4'},
    {text: 'Работа в ИТ', id: 'direction_intern_5'},
    {text: 'Продажи', id: 'direction_intern_6'},
    {text: 'Финансы', id: 'direction_intern_7'},
    {text: 'Юриспруденция', id: 'direction_intern_8'},
    {text: 'Управление продуктами', id: 'direction_intern_9'},
];

export const DIRECTIONS_JOB = [
    {text: 'HR', id: 'direction_job_0'},
    {text: 'Административный персонал', id: 'direction_job_1'},
    {text: 'Аналитика', id: 'direction_job_2'},
    {text: 'Дизайн', id: 'direction_job_3'},
    {text: 'Маркетинг и PR', id: 'direction_job_4'},
    {text: 'Работа в ИТ', id: 'direction_job_5'},
    {text: 'Продажи', id: 'direction_job_6'},
    {text: 'Технический блок', id: 'direction_job_7'},
    {text: 'Финансы', id: 'direction_job_8'},
    {text: 'Юриспруденция', id: 'direction_job_9'},
    {text: 'Безопасность', id: 'direction_job_10'},
    {text: 'Поддержка', id: 'direction_job_11'},
    {text: 'Розничная сеть', id: 'direction_job_12'},
    {text: 'Управление продуктами', id: 'direction_job_13'},
];

export const SKILLS_INTERN = [
    {text: 'Microsoft Office (Word, Excel, Power Point)', id: 'skill_intern_0'},
    {text: 'Figma', id: 'skill_intern_1'},
    {text: 'SQL', id: 'skill_intern_2'},
    {text: 'Python', id: 'skill_intern_3'},
    {text: 'SOLID', id: 'skill_intern_4'},
    {text: 'Java', id: 'skill_intern_5'},
    {text: 'JavaScript', id: 'skill_intern_6'},
    {text: 'Kafka', id: 'skill_intern_7'},
    {text: 'Power BI', id: 'skill_intern_8'},
    {text: 'C#', id: 'skill_intern_10'},
    {text: 'GoLang', id: 'skill_intern_11'},
    {text: 'Протокол HTTP/S', id: 'skill_intern_12'},
    {text: 'Основы Linux', id: 'skill_intern_13'},
    {text: 'CI/CD', id: 'skill_intern_14'},
    {text: 'Aris, Sparx sistems, Erwin/BPwin, Archi, BPMN Modeler', id: 'skill_intern_15'},
    {text: 'Инженерные навыки', id: 'skill_intern_16'},
    {text: 'Основы законодательства', id: 'skill_intern_17'},
    {text: 'Коммуникабельность', id: 'skill_intern_18'},
    {text: 'Копирайтинг', id: 'skill_intern_19'},
    {text: 'Документооборот (ЭДО)', id: 'skill_intern_20'},
    {text: 'Oracle', id: 'skill_intern_21'},
    {text: 'Hyperion Planning', id: 'skill_intern_22'},
    {text: 'UI/UX-дизайн', id: 'skill_intern_23'},
];

export const SKILLS_JOB = [
    {text: 'Microsoft Office (Word, Excel, Power Point)', id: 'skill_job_0'},
    {text: 'Figma', id: 'skill_job_1'},
    {text: 'SQL', id: 'skill_job_2'},
    {text: 'Python', id: 'skill_job_3'},
    {text: 'SOLID', id: 'skill_job_4'},
    {text: 'Java', id: 'skill_job_5'},
    {text: 'JavaScript', id: 'skill_job_6'},
    {text: 'Kafka', id: 'skill_job_7'},
    {text: 'Power BI', id: 'skill_job_8'},
    {text: 'C#', id: 'skill_job_10'},
    {text: 'GoLang', id: 'skill_job_11'},
    {text: 'Протокол HTTP/S', id: 'skill_job_12'},
    {text: 'Основы Linux', id: 'skill_job_13'},
    {text: 'CI/CD', id: 'skill_job_14'},
    {text: 'Aris, Sparx sistems, Erwin/BPwin, Archi, BPMN Modeler', id: 'skill_job_15'},
    {text: 'Инженерные навыки', id: 'skill_job_16'},
    {text: 'Основы законодательства', id: 'skill_job_17'},
    {text: 'Коммуникабельность', id: 'skill_job_18'},
    {text: 'Копирайтинг', id: 'skill_job_19'},
    {text: 'Oracle', id: 'skill_job_20'},
    {text: 'Hyperion Planning', id: 'skill_job_21'},
    {text: 'UI/UX-дизайн', id: 'skill_job_22'},
    {text: 'MITRE ATT&CK, Cyber KillChain', id: 'skill_job_23'},
    {text: 'Jira', id: 'skill_job_24'},
    {text: '1С', id: 'skill_job_25'},
    {text: 'Adobe Photoshop', id: 'skill_job_26'},
    {text: 'OSS/BSS', id: 'skill_job_27'},
    {text: 'Hyperion', id: 'skill_job_28'},
    {text: 'Thinkcell', id: 'skill_job_29'},
    {text: 'МСФО или РСБУ', id: 'skill_job_30'},
];

export const EMAIL_REG_EXP = /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/;

export const GOOGLE_DATA = {
    'int': {
        url: 'https://docs.google.com/forms/u/0/d/e/1FAIpQLSeUwxPV61sw_zXSHBHdmCqY-yQ7ItPx-ut7O46j58udp7m8bg/formResponse',
        name: 'entry.1161791459',
        surname: 'entry.1936737489',
        email: 'entry.559446625',
        direction: 'entry.1523286373',
        skills: 'entry.1404342195',
    },
    'job': {
        url: 'https://docs.google.com/forms/u/0/d/e/1FAIpQLSc5nIF1SbMFYRXMy5kY3WJrnkNwQ-AzO6h98EDI3ku0jeYz1A/formResponse',
        name: 'entry.1161791459',
        surname: 'entry.1936737489',
        email: 'entry.559446625',
        direction: 'entry.1523286373',
        skills: 'entry.1404342195',
        exp: 'entry.1115049009',
    }
};
